kind: pipeline
name: cliente_deploy

steps: 
  - name: buildA1
    image: node:10.7.0
    commands:
     - npm install -g grunt-cli bower
     - npm install natives
     - npm install
     - bower install --allow-root
     - grunt build
    when:
      branch:
      - master
      - test
      event:
      - push
      - pull_request

  - name: publish-s3-test  
    image: plugins/s3
    settings:
      bucket: cliente-pruebas
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key
      region: us-east-1
      source: dist/**/*
      target: /pruebas${DRONE_REPO_NAME%%_cliente}.portaloas.udistrital.edu.co
      strip_prefix: dist/
    when:
      branch:
      - test
      event:
      - push
      - pull_request

  - name: publish-s3-master  
    image: plugins/s3
    settings:
      bucket: cliente-pruebas
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key
      region: us-east-1
      source: dist/**/*
      target: /${DRONE_REPO_NAME%%_cliente}.portaloas.udistrital.edu.co
      strip_prefix: dist/
    when:
      branch:
      - master
      event:
      - push
      - pull_request


  - name: NotifyTelegram
    image: appleboy/drone-telegram
    settings:
      token:
        from_secret: telegram_token
      to:
        from_secret: telegram_to
      format: html
      message: >
        {{#success build.status}} <p>With Drone 1.0</p> 
          <code>{{repo.owner}}/{{repo.name}}</code> <a href="{{build.link}}">SUCCESS</a> 
          <code>{{commit.branch}}</code>@<a href="{{commit.link}}">{{truncate commit.sha 7}}</a>
        {{else}}
          <code>{{repo.owner}}/{{repo.name}}</code> <a href="{{build.link}}">FAILURE</a>
          <code>{{commit.branch}}</code>@<a href="{{commit.link}}">{{truncate commit.sha 7}}</a>
        {{/success}}
    when:
      status:
      - failure
      - success
