"use strict";

/**
 * @ngdoc function
 * @name contractualClienteApp.decorator:TextTranslate
 * @description
 * # TextTranslate
 * Decorator of the contractualClienteApp
 */
var text_es = {
  BTN: {
    VER: "Ver",
    SELECCIONAR: "Seleccionar",
    CANCELAR: "Cancelar",
    CONFIRMAR: "Confirmar",
    AGREGAR: "Agregar",
    REGISTRAR: "Registrar",
    SOLICITAR_RP:"Solicitar RP",
    QUITAR_RUBRO: "Quitar",
    VER_SEGUIMIENTO_FINANCIERO:"Ver seguimiento financiero",
    APROBAR: "Aprobar",
    RECHAZAR: "Rechazar",
    SOLICITAR_CDP: "Solicitar CDP"
  },
  TITULO: "GENERATOR-OAS",
  MENSAJE_INICIAL: "Ahora puede comenzar con el desarrollo ...",
  SELECCIONAR: "Seleccionar",
  //solicitud_necesidad
  NECESIDADES: "Necesidades",
  NECESIDAD: "Necesidad",
  SOLICITUD: "Solicitud",
  SOLICITUD_NECESIDAD: "Solicitud de Necesidad",
  DURACION: "Duración",
  UNICO_PAGO: "Único Pago",
  HASTA_AGOTAR_PRESUPUESTO: "Hasta Agotar Presupuesto",
  AÑOS: "Años",
  MESES: "Meses",
  DIAS: "Días",
  RESPONSABLES: "Responsables",
  DEPENDENCIA_SOLICITANTE: "Dependencia Solicitante",
  JEFE_DEPENDENCIA_SOLICITANTE: "Jefe Dependencia Solicitante",
  DEPENDENCIA_DESTINO: "Dependencia Destino",
  JEFE_DEPENDENCIA_DESTINO: "Jefe Dependencia Destino",
  ROL: "Rol",
  ORDENADOR_GASTO: "Ordenador del Gasto",
  GENERAL: "General",
  PLAN_ANUAL_ADQUISICIONES: "Plan Anual de Adquisiones",
  ESTUDIO_MERCADO: "Estudio de Mercado",
  ANALISIS_RIESGOS: "Análisis de Riesgos",
  SUPERVISOR: "Supervisor",
  OBJETO_CONTRACTUAL: "Objeto Contractual",
  OBJETO_CONTRATO: "Objeto de Contrato",
  JUSTIFICACION_CONTRATO: "Justificación de Contrato",
  DOCUMENTOS: "Documentos",
  ENLACE: "Enlace",
  ESPECIFICACIONES: "Especificaciones",
  TIPO_SERVICIO: "Tipo de Servicio",
  PERFIL: "Perfil",
  EL_TIPO_DE: "el Tipo de",
  SNIES_AREA: "Snies Área",
  SNIES_NUCLEO_BASICO: "Snies Núcleo Básico",
  CANTIDAD: "Cantidad",
  ACTIVIDADES_ESPECIFICAS: "Actividades Específicas",
  ELEMENTOS: "Elementos",
  ELEMENTO: "Elemento",
  UNIDAD_MEDIDA: "Unidad de Medida",
  VALOR_UNITARIO: "Valor Unitario",
  IVA: "IVA",
  VALOR_IVA: "Valor IVA",
  VALOR_TOTAL: "Valor Total",
  REQUISITOS_MINIMOS: "Requisitos mínimos",
  FINANCIACION: "Financiación",
  TIPO_RUBRO: "Tipo de Rubro",
  VALOR_SOLICITADO: "Valor Solicitado",
  TOTAL_FINANCIACION: "Total Financiación",
  //lista_documentos_legales
  MARCO_LEGAL: "Marco Legal",
  NOMBRE_DOCUMENTO: "Nombre del Documento",
  VER: "Ver",
  //lista_actividades_economicas
  ACTIVIDADES_ECONOMICAS: "Actividades Económicas",
  //lista_subgrupos_catalogos
  CATALOGO: "Catálogo",
  PRODCUTOS: "Productos",
  //lista_apropiaciones
  APROPIACIONES: "Apropiaciones",
  APROPIACIONES_VIGENCIA: "Apropiaciones de la Vigencia",
  CODIGO_RUBRO: "Código del Rubro",
  DESCRIPCION_RUBRO: "Descripción del Rubro",
  SALDO: "Saldo",
  //fuentes_apropiacion
  FUENTES_FINANCIAMIENTO_APROPIACION: "Fuentes de Financiamiento de la Apropiación",
  //necesidades
  GESTION_NECESIDADES: "Gestión de Necesidades",
  NUMERO_ELABORACION: "No. de Elaboración",
  //visualizar_necesidad
  DE: "de",
  MONTO: "Monto",
  //SOLICITUD RP
  ERROR: "Error",
  SALIR:"Salir",
  VOLVER_CONTRATOS: "Volver a contratos",
  NUMERO_SOLICITUD:"Número solicitud",
  INSERCION_RP:"Se insertó correctamente la solicitud del registro presupuestal con los siguientes datos",
  VIGENCIA_SOLICITUD: "Vigencia solicitud",
  FECHA_SOLICITUD: "Fecha solicitud",
  NUMERO_CONTRATO: "Número contrato",
  SELECCIONE_UNA_VIGENCIA:"Seleccione una vigencia diferente",
  RESPONSABLE_DOCUMENTO: "Responsable documento",
  RESPONSABLE: "Responsable",
  DATOS_APROPIACIONES: "Datos de las apropiaciones",
  MODALIDAD_SELECCION: "Modalidad de Selección",
  CONTRATO: "Contrato",
  VIGENCIA_CONTRATO: "Vigencia contrato",
  FUENTE:"Fuente de Financiamiento",
  SOLICITUD_PERSONAS:"Contratos para solicitud del registro presupuestal",
  VIGENCIA_ACTUAL:"Vigencia Actual ",
  VIGENCIA_SELECCIONADA:"Vigencia Seleccionada ",
  SELECCION_CDP:"Selección de CDP",
  UNIDAD_EJECUTORA:"Unidad ejecutora",
  ESTADO:"Estado",
  SELECCION_COMPROMISO:"Selección de Compromiso",
  SOLICITUD_RP: "Solicitud Registro Presupuestal",
  DATOS_RP:"Datos del Registro Presupuestal",
  BENEFICIARIO:"Beneficiario",
  NOMBRE_CONTRATISTA: "Nombre",
  DOCUMENTO_CONTRATISTA: "No Documento",
  NOMBRE: "Nombre",
  FUENTE_FINANCIAMIENTO: "Fuente Financiamiento",
  VALOR: "Valor",
  COMPROMISO: "Compromiso",
  NUMERO:"Número",
  VIGENCIA:"Vigencia",
  COMPROMISO_TIPO:"Tipo",
  VALOR_RP:"Valor registro presupuestal",
  SALDO_AP:"Saldo apropiación",
  CDP:"CDP",
  CODIGO: "Código",
  CONSECUTIVO:"Consecutivo",
  OBJETIVO:"Objetivo",
  OBJETO:"Objeto",
  ORDENADOR:"Ordenador",
  //SEGUMIENTO FINANCIERO
  SEGUIMIENTO_FINANCIERO:"Seguimiento financiero del contrato",
  DATOS_CONTRATO:"Datos contrato",
  ORDENES_PAGO: "Órdenes pago",
  ESTADISTICAS : "Estadísticas",
  DATOS_FINANCIEROS_CONTRATO: "Datos financieros del contrato",
  DATOS_CONTRATISTA: "Datos contratista",
  APELLIDOS: "Apellidos",
  NOMBRES: "Nombres",
  TIPO_DOCUMENTO: "Tipo documento",
  NUMERO_DOCUMENTO : "No documento",
  FECHA_INICIO:"Fecha inicio",
  FECHA_FIN:"Fecha fin",
  FECHA:"Fecha",
  TIPO:"Tipo",
  DATOS_REGISTRO_PRESUPUESTAL:"Datos del registro presupuestal",
  NUMERO_REGISTRO_PRESUPUESTAL: "No RP",
  NOMBRE_REGISTRO_PRESUPUESTAL: "Nombre RP",
  NUMERO_DISPONIBILIDAD: "No CDP",
  NOMBRE_DISPONIBILIDAD: "Nombre CDP",
  ORDEN_PAGO: "Orden pago",
  FECHA_ORDEN: "Fecha orden",
  VALOR_BRUTO: "Valor bruto",
  LINEA_ORDEN_PAGO:"Linea del tiempo de ordenes de pago",
  ESTADISTICAS_GENERALES: "Estadísticas generales",
  VALOR_TOTAL_CONTRATO: "Valor total contrato",
  VALOR_MENSUAL: "Valor mensual",
  VALOR_TOTAL_PAGADO:"Valor total pagado",
  VALOR_RESTANTE:"Valor restante",
  PORCENTAJE_PAGADO:"Porcentaje pagado",
  PORCENTAJE_RESTANTE:"Porcentaje restante",
  PORCENTAJE:"Porcentaje",
  GRAFICO_BARRAS_CONTRATO:"Gráfico de barras del contrato",
  CARGO:"Cargo",
  NUMERO_COMPROMISO:"No compromiso" ,
  FECHA_REGISTRO: "Fecha registro",
  VIGENCIA_PRESUPUESTO: "Vigencia presupuesto",
  PRESUPUESTO: "Presupuesto",
  VALOR_ORDEN:"Valor orden",
  VALOR_NETO:"Valor neto",
  VIGENCIA_ORDEN: "Vigencia orden",
  SELECCIONAR_ORDEN_PAGO:"Seleccione una orden de pago",
  NO_CDP_REGISTRADAS: "No existe disponibilidades o registros presupuestales registradas para este contrato",
  POR_FAVOR_ESPERE:"Por favor espere",
  CARGANDO_DATOS: "Los datos se están cargando",
  VALOR_ACUMULADO: "Valor acumulado",
  PORCENTAJE_ORDEN: "Porcentaje orden",
  PORCENTAJE_ACUMULADO: "Porcentaje acumulado",
  ORDEN:"Orden",
  ACUMULADO:"Acumulado",
  TOTAL:"Total",
  UNITARIO:"Unitario",
  NO_HAY_DATOS_REDIRIGIR:"No hay datos para mostrar, será redirigido al menú anterior",








  /*
    contrato_detalle.html
    */
    INFORMACION_CONTRATO: "Información contrato",   
    VIGENCIA: "Vigencia",
    FORMA_PAGO: "Forma de pago",  
    SEDE_SOLICITANTE: "Sede solicitante",
    NUMERO_CDP: "Número de CDP",
    NUMERO_NECESIDAD: "Número de necesidad",
    OBJETO_CDP: "Objeto del CDP",
    JUSTIFICACION: "Justificación",
    DESCRIPCION_FORMA_PAGO: "Descripción forma de pago",
    UNIDAD_EJECUTORA: "Unidad ejecutora",
    MARCO_LEGAL: "Marco legal",
    OBJETO: "Objeto",
    OBSERVACIONES: "Observaciones",
    /*
    Contrato_resumen.html
    */
    DOCENTES_CONTRATADOS: "Docentes contratados - periodo actual",
    NOMBRE: "Nombre",
    CEDULA: "Cédula",
    EXPEDICION: "Expedida",
    CATEGORIA: "Categoría",
    DEDICACION: "Dedicación",
    HORAS_SEMANALES: "Horas semanales",
    PERIODO_VINCULACION: "Periodo vinculación",
    VALOR_CONTRATO: "Valor del contrato",
  /*
  Contrato_registro.html
  */
  DATOS_BASICOS: "Información básica del contrato",
  DISPONIBILIDAD: "Disponibilidad",
  JUSTIFICACION_Y_OBSERVACIONES: "Justificación y observaciones",
    /*
    Experiencia_laboral_detalle.html
    */
    EXPERIENCIA_LABORAL_DOCENTE: "Experiencia laboral docente",
    TIPO_ACTIVIDAD: "Tipo de actividad",
    CAMPO_ENSEÑANZA: "Campo de enseñanza",
    INICIO: "Inicio",
    FINALIZACION: "Finalización",
    INSTITUCION: "Institución",
    PAIS: "País",
    DEPARTAMENTO: "Departamento",
    MUNICIPIO: "Municipio",
    LOCALIDAD: "Localidad",
    TIPO_DEDICACION: "Tipo de dedicación",
    /*
    formacion_academica.html
    */
    FORMACION_ACADEMICA: "Formación académica",
    NOMBRE_PROYECTO: "Nombre del proyecto",
    AREA_CONOCIMIENTO: "Área del conocimiento",
    TITULO_DOCENTE: "Título",
    /*
    hojas_vida_seleccion.html
    */
    HOJAS_VIDA: "Hojas de vida",
    HOJAS_VIDA_INSCRITAS: "Hojas de vida inscritas",
    INFORMACION_BASICA_CONTRATO: "Información  básica del contrato",
    TENGA_CUENTA: "Tenga en cuenta",
    PROYECTO_CURRICULAR: "Proyecto curricular",
    NUMERO_SEMANAS: "Número de semanas",
    NUMERO_HORAS_SEMANALES: "Número de horas semanales",
    DEDICACION: "Dedicación",
    DOCENTE_PLANTA: "Docente de planta",
    DOCENTE_VINCULADOS: "Docentes vinculados",
    
    /*
    Informacion_personal.html
    */
    INFORMACION_PERSONAL: "Información personal",
    DOCUMENTO: "Documento",
    FECHA_EXPEDICION: "Fecha de expedición",
    PRIMER_NOMBRE: "Primer nombre",
    SEGUNDO_NOMBRE: "Segundo nombre",
    PRIMER_APELLIDO: "Primer apellido",
    SEGUNDO_APELLIDO: "Segundo apellido",
    PAIS_NACIMIENTO: "País de nacimiento",
    ESTADO_CIVIL: "Estado civil",
    /*
    persona_natural_detalle.html
    */    
    INFORMACION_PERSONA_NATURAL: "Información persona natural",
    CIUDAD_EXPEDICION: "Ciudad de expedición",
    GENERO: "Genero",
    /*
    resolucion_detalle-html
    */
    RESOLUCION: "Resolución",
    FORMATO_RESOLUCION: "Formato de resolución",
    VER_DOCENTES: "Ver docentes contratados",
    NUMERO_RESOLUCION: "Número de resolución",
    FACULTAD: "Facultad",
    NIVEL_ACADEMICO: "Nivel académico",
    PREAMBULO: "Preámbulo",
    CONSIDERANDO: "Considerando",
    VISTA_RESOLUCION: "Vista de la resolución",
    VISTA_RESOLUCION_ACTUALIZADA: "Vista de la resolución actualizada",
    RESUELVE: "Resuelve",
    ARTICULO: "Artículo",
    TEXTO: "Texto",
    PARAGRAFO: "Parágrafo",
    /*
    res_generacion.html
    */
    GENERACION_RESOLUCION: "Generación resolución",
    SELECCIONE: "Seleccione",
    CONSIDERACION: "Consideración",
    RESOLUCIONES: "Resoluciones",
    LISTA_RESOLUCIONES: "Lista de resoluciones",
    /*
    trabajos_investigacion.html
    */
    TRABAJOS_INVESTIGACION: "Trabajos de investigación",
    NOMBRE_INVESTIGACION: "Nombre de la investigación",
    AREA_INVESTIGACION: "Área de la investigación",
    TIPO_INVESTIGACION: "Tipos de investigación",
    /*
    resolucion_lista.html
    */
    BTN: {
      CREAR_RESOLUCION: "Crear nueva resolución de vinculación especial",
      GENERAR_RESOLUCION: "Generar Resolución",
      REALIZAR_EXPEDICION: "Realizar expedición de la resolución con los datos introducidos",
      INFORMACION_PERSONA_NATURAL: "Información persona natural",
      VINCULAR_DOCENTES_SELECCIONADOS: "Vincular docentes seleccionados a la resolución",
      FORMACION_ACADEMICA: "Formación académica",      
      EXPERIENCIA_LABORAL_DOCENTE: "Experiencia laboral docente",
      TRABAJOS_INVESTIGACION: "Trabajos de investigación",
    },     
    /*
    Scrits
    Hoja de vida seleccion.js
    */
    ALERTA: "Alerta",
    ACEPTAR: "Aceptar",
    MENSAJE_ERROR: "No se han podido encontrar datos de la persona seleccionada",
    NUMERO_VINCULACIONES: "Número de vinculaciones realizadas: ",
    VALOR_CONTRATO_FORMATO: "Valor del contrato: $",
    MONEDA_CORRIENTE: " (Moneda corriente: ",
    SALARIO_NO_CALCULADO1: "El salario de ",
    SALARIO_NO_CALCULADO2: " no ha podido ser calculado",
    VALIDAR_CONTRATO: "Los valores asignados no son validos para la resolución actual, por favor remitarse a la pestaña tenga en cuenta para poder ver las reglas.",
    DOCUMENTO_ID: "DOCUMENTO",
    REGISTRAR_CONTRATOS: "Existen docentes con una vinculacion asociada a la resolución actual, ¿desea continuar con la vinculacion?",
    AGREGAR_CONTRATO: "Agregar nuevo contrato",
    CANCELAR: "Cancelar",
    CANCELADO: "Cancelado",
    REGISTRO_CANCELADO: "El registro ha sido cancelado",
    PREGUNTA_SEGURO: "¿Está seguro?",
    CONFIRMAR_DESVINCULACION: "Desea confirmar la desvinculación del docente",
    DEVINCULAR_DOCENTE: "Desvincular docente",
    DESVINCULACION_CANCELADA: "La desvinculación ha sido cancelada",
    HCH: "Hora cátedra honorarios: ",
    HCH1: "Entre 4 y 8 horas semanales.",
    HCP: "Hora cátedra prestaciones: ",
    HCP1: "Entre 8 y 16 horas semanales.",
    MTO: "Medio tiempo ocasional: ",
    MTO1: "Entre 16 y 20 horas semanales.",
    TCO: "Tiempo completo ocasional: ",
    TCO1: "Entre 24 y 40 horas semanales.",
    SEMANAS: "Semanas",
    REGLAS: "Reglas",
    PROBLEMA: "Problem",
    VER_INFO_PERSONAL_BTN: "Ver información personal",
    VER_INFO_ACADEMICA: "Ver información académica",
    VER_EXP_LABORAL: "Ver experiencia laboral",
    VER_TRABAJOS_INVESTIGACION: "Ver trabajos de investigación",
    BORRAR_BTN: "Borrar",
    UN: "UN",
    DOS: "DOS",
    TRES: "TRES",
    CUATRO: "CUATRO",
    CINCO: "CINCO",
    SEIS: "SEIS",
    SIETE: "SIETE",
    OCHO: "OCHO",
    NUEVE: "NUEVE",
    DIEZ: "DIEZ",
    ONCE: "ONCE",
    DOCE: "DOCE",
    TRECE: "TRECE",
    CATORCE: "CATORCE",
    QUINCE: "QUINCE",

    DIECISEIS: "DIECISEIS",
    DIECISIETE: "DIECISIETE",
    DIECIOCHO: "DIECIOCHO",
    DIECINUEVE: "DIECINUEVE",


    VEINTE: "VEINTE",

    VEINTIUNO: "TWENTY ONE",
    VEINTIDOS: "VEINTIUNO",
    VEINTITRES: "VEINTITRES",
    VEINTICUATRO: "VEINTICUATRO",
    VEINTICINCO: "VEINTICINCO",
    VEINTISEIS: "VEINTISEIS",
    VEINTISIETE: "VEINTISIETE",
    VEINTIOCHO: "VEINTIOCHO",
    VEINTINUEVE: "VEINTINUEVE",

    TREINTA: "TREINTA",
    CUARENTA: "CUARENTA",
    CINCUENTA: "CINCUENTA", 
    SESENTA: "SESENTA",
    SETENTA: "SETENTA",
    OCHENTA: "OCHENTA",
    NOVENTA: "NOVENTA",
    CIENTO: "CIENTO ",
    CIEN: "CIEN",
    DOSCIENTOS: "DOSCIENTOS ",
    TRESCIENTOS: "TRESCIENTOS ",
    CUATROCIENTOS: "CUATROCIENTOS ",
    QUINIENTOS: "QUINIENTOS ",
    SEISCIENTOS: "SEISCIENTOS ",
    SETECIENTOS: "SETECIENTOS ",
    OCHOCIENTOS: "OCHOCIENTOS ",
    NOVECIENTOS: "NOVECIENTOS ",
    UN_MIL: "UN MIL", 
    MIL: "MIL",
    UN_MILLON: "UN MILLON", 
    MILLONES: "MILLONES",
    PESOS: "PESOS",
    PESO: "PESO",
    CON: "CON",
    CERO: "CERO",
    Y: " Y ",
    /*
    resolucion_lista.js
    */
    VISTA_PREVIA_RESOLUCION: "Vista previa de la resolución",    
    NIVEL: "Nivel",
    /*
    contrato_registro.js
    */
    NO_CALCULADO_SALARIO: "El salario no ha podido ser calculado",
    NUMERO: "Número",
    EXPEDIR: "¿Expedir la resolución?",
    SEGURO_EXPEDIR: "¿Esta seguro que desea expedir la resolución?",
    EXPEDICION_NO_REALIZADA: "No se ha realizado la expedición de la resolución",
    EXPEDIDA: "La resolución ha sido expedida con exito",
    DATOS_REGISTRADOS: "Los datos de las vinculaciones realizadas han sido registradas con exito",
    PROBLEMA_EXPEDICION: "Se ha presentado un problema en la expedición de la resolución",
    PROBLEMA_DOCENTE_CONTRATADOS: "Se ha presentado un problema en el registro de los datos de los docentes contratados",
    NO_DOCENTES: "No hay docentes inscritos dentro de la resolución",
    
    /*
    resolucion_detalle.js
    */
    ESCRIBA_TEXTO: "Escriba el texto del artículo",
    DEBE_INSERTAR: "Debe insertar texto.",
    ALMENOS_UNO: "La resolución debe tener al menos un artículo",
    ESCRIBA_PARAGRAFO: "Escriba el texto del paragrafo",
    GUARDADO: "Guardado",
    GUARDADO_EXITO: "Los cambios se han guardado exitosamente",
    PROBLEMA_ALMACENAMIENTO: "Ha habido un problema en el almacenamiento de los cambios",
    REVISE_DATOS_RESOLUCION: "Revise los datos de la resolución",    
    /*
    resolucion_administracion.js
    */
    NO_RESTAURACION_RESOLUCION: "No se ha realizado la restauración de la resolución",
    NO_CANCELADA_PAGOS: "La resolucion no puede ser cancelada debido a que hay pagos asociados a las vinculaciones.",
    NO_CANCELACION_RESOLUCION: "No se ha realizado la cancelación de la resolución.",
    PREGUNTA_RESTAURAR: "¿Restaurar la resolución?",
    CANCELAR_RESOLUCION: "¿Cancelar la resolución?",
    OPCIONES: "Opciones",
    VER_BTN: "Ver",
    EDITAR_BTN: "Editar",
    CONFIGURAR_BTN: "Configurar",
    EXPEDIR_BTN: "Expedir",
    CANCELAR_BTN: "Cancelar resolución",
    RESTAURAR_BTN: "Restaurar resolución",
    /*
    contrato_resumen.html
    */
    DOCENTES_CONTRATADOS_ACTUAL: "DOCENTES CONTRATADOS - PERIODO ACTUAL",

};

var text_en = {
  TITULO: "GENERATOR-OAS",
  MENSAJE_INICIAL: "Now get to start to develop ...",
  BTN: {
    VER: "See",
    SELECCIONAR: "Choose",
    CANCELAR: "Cancel",
    CONFIRMAR: "Confirm",
    AGREGAR: "Add",
    REGISTRAR: "Register",
    SOLICITAR_RP:"RP request",
    QUITAR_RUBRO: "Delete",
    APROBAR: "Approbe",
    RECHAZAR: "Reject",
    SOLICITAR_CDP: "CDP Request",
    VER_SEGUIMIENTO_FINANCIERO:"See financial monitoring"
  },
  SELECCIONAR: "Select",
  NECESIDADES: "Needs",
  NECESIDAD: "Need",
  //SOLICITUD RP
  ERROR: "Error",
  SALIR:"Exit",
  VOLVER_CONTRATOS: "Back to contracts",
  NUMERO_SOLICITUD:"Request number",
  INSERCION_RP:"The budget register request was insert correctly with the following data:",
  VIGENCIA_SOLICITUD: "Request validity",
  FECHA_SOLICITUD: "Request date",
  NUMERO_CONTRATO: "Contract number",
  SOLICITUD: "Request",
  SOLICITUD_NECESIDAD: "Need Request",
  DURACION: "Duration",
  UNICO_PAGO: "Single Payment",
  HASTA_AGOTAR_PRESUPUESTO: "Until the Budget Had Been Used Up",
  AÑOS: "Years",
  MESES: "Months",
  DIAS: "Days",
  RESPONSABLES: "Responsible",
  DEPENDENCIA_SOLICITANTE: "Requesting Unit",
  JEFE_DEPENDENCIA_SOLICITANTE: "Boss of Requesting Unit",
  DEPENDENCIA_DESTINO: "Destination Unit",
  JEFE_DEPENDENCIA_DESTINO: "Boss of Destination Unit",
  ROL: "Role",
  ORDENADOR_GASTO: "Expenditure Authorizer",
  GENERAL: "General",
  PLAN_ANUAL_ADQUISICIONES: "Annual Procurement Plan",
  ESTUDIO_MERCADO: "Market Survey",
  ANALISIS_RIESGOS: "Risk Analysis",
  SUPERVISOR: "Supervisor",
  OBJETO_CONTRACTUAL: "Contractual Object",
  OBJETO_CONTRATO: "Contract Object",
  JUSTIFICACION_CONTRATO: "Contract Justification",
  DOCUMENTOS: "Documents",
  ENLACE: "Link",
  ESPECIFICACIONES: "Specifications",
  TIPO_SERVICIO: "Type of Service",
  PERFIL: "Profile",
  EL_TIPO_DE: "the Type of",
  SNIES_AREA: "Snies Area",
  SNIES_NUCLEO_BASICO: "Snies Basic Core",
  CANTIDAD: "Quantity",
  ACTIVIDADES_ESPECIFICAS: "Specific Activities",
  ELEMENTOS: "Elements",
  ELEMENTO: "Element",
  UNIDAD_MEDIDA: "Unit of Measurement",
  VALOR_UNITARIO: "Unit Value",
  IVA: "IVA",
  VALOR_IVA: "IVA Value",
  VALOR_TOTAL: "Total Value",
  REQUISITOS_MINIMOS: "Minimum Requirements",
  FINANCIACION: "Financing",
  TIPO_RUBRO: "Type of Line Item",
  VALOR_SOLICITADO: "Requested Value",
  TOTAL_FINANCIACION: "Total Financing",
  //lista_documentos_legales
  MARCO_LEGAL: "Legal Framework",
  NOMBRE_DOCUMENTO: "Document Name",
  VER: "Details",
  //lista_actividades_economicas
  ACTIVIDADES_ECONOMICAS: "Economic Activities",
  //lista_subgrupos_catalogos
  CATALOGO: "Catalogue",
  PRODCUTOS: "Products",
  //lista_apropiaciones
  APROPIACIONES: "Appropiations",
  APROPIACIONES_VIGENCIA: "Validity Appropiations of",
  CODIGO_RUBRO: "Line Item Code",
  DESCRIPCION_RUBRO: "Line Item Description",
  SALDO: "Balance",
  //fuentes_apropiacion
  FUENTES_FINANCIAMIENTO_APROPIACION: "Appropiations Funding Source",
  //necesidades
  GESTION_NECESIDADES: "Managment Needs",
  NUMERO_ELABORACION: "No. of Elaboration",
  //visualizar_necesidad
  DE: "of",
  MONTO: "Amount",
  //SOLICITUD RP
  RESPONSABLE_DOCUMENTO: "Person responsible identification",
  SELECCIONE_UNA_VIGENCIA:"Choose a diferente validity",
  RESPONSABLE: "Person responsible",
  DATOS_APROPIACIONES: "Appropiation data",
  MODALIDAD_SELECCION: "Selection method",
  CONTRATO: "Contract",
  VIGENCIA_CONTRATO: "Contract validity",
  FUENTE:"Source",
  SOLICITUD_PERSONAS:"Contracts for budget registers",
  VIGENCIA_ACTUAL:"Current validity",
  VIGENCIA_SELECCIONADA:"Chosen validity",
  SELECCION_CDP:"CDP choise",
  UNIDAD_EJECUTORA:"Performer unity",
  ESTADO:"State",
  SELECCION_COMPROMISO:"Agreement choose",
  SOLICITUD_RP: "Budget register request",
  DATOS_RP:"Buget register data",
  BENEFICIARIO:"Beneficiary",
  NOMBRE_CONTRATISTA: "Name",
  DOCUMENTO_CONTRATISTA: "Identification",
  NOMBRE: "Name",
  FUENTE_FINANCIAMIENTO: "Funding source",
  VALOR: "Value",
  COMPROMISO: "Agreement",
  NUMERO:"Number",
  VIGENCIA:"Validity",
  COMPROMISO_TIPO:"Tipe",
  VALOR_RP:"Budget register value",
  SALDO_AP:"Appropiation reminder",
  CDP:"CDP",
  CODIGO: "Code",
  CONSECUTIVO:"Consecutive",
  OBJETIVO:"Objective",
  OBJETO:"Object",
  ORDENADOR:"Authorizer",
  //SEGUMIENTO FINANCIERO
  SEGUIMIENTO_FINANCIERO:"Financial monitoring of the contract",
  DATOS_CONTRATO:"Contract data",
  ORDENES_PAGO: "Pay orders",
  ESTADISTICAS : "Statistics",
  DATOS_FINANCIEROS_CONTRATO: "Financial data of the contract",
  DATOS_CONTRATISTA: "Contractor data",
  APELLIDOS: "Surnames",
  NOMBRES: "Names",
  TIPO_DOCUMENTO: "Identification type",
  NUMERO_DOCUMENTO : "Document number",
  FECHA_INICIO:"Start date",
  FECHA_FIN:"End date",
  FECHA:"Date",
  TIPO:"Type",
  DATOS_REGISTRO_PRESUPUESTAL:"Budget register data",
  NUMERO_REGISTRO_PRESUPUESTAL: "Budget register number",
  NOMBRE_REGISTRO_PRESUPUESTAL: "Budget register name",
  NUMERO_DISPONIBILIDAD: "Availability number",
  NOMBRE_DISPONIBILIDAD: "Availability name",
  ORDEN_PAGO: "Pay order",
  FECHA_ORDEN: "Order date",
  VALOR_BRUTO: "Gross value",
  LINEA_ORDEN_PAGO:"Pay orders timeline",
  ESTADISTICAS_GENERALES: "General statistics",
  VALOR_TOTAL_CONTRATO: "Contract total value",
  VALOR_MENSUAL: "Monthly value",
  VALOR_TOTAL_PAGADO:"Paid total value",
  VALOR_RESTANTE:"Remaining value",
  PORCENTAJE_PAGADO:"Paid percentage",
  PORCENTAJE_RESTANTE:"Remaining percentage",
  PORCENTAJE:"Percentage",
  GRAFICO_BARRAS_CONTRATO:"Contract bar graph",
  CARGO:"Position",
  NUMERO_COMPROMISO:"Compromise number" ,
  FECHA_REGISTRO: "Register date",
  VIGENCIA_PRESUPUESTO: "Budget validity",
  PRESUPUESTO: "Budget",
  VALOR_ORDEN:"Order value",
  VALOR_NETO:"Net value",
  VIGENCIA_ORDEN: "Validity order",
  SELECCIONAR_ORDEN_PAGO:"Choose a pay order",
  NO_CDP_REGISTRADAS: "There are not availabilities registered for this contract",
  POR_FAVOR_ESPERE:"Please wait",
  CARGANDO_DATOS: "Data is loading",
  VALOR_ACUMULADO: "Accumulate value",
  PORCENTAJE_ORDEN: "Order percentage",
  PORCENTAJE_ACUMULADO: "Accumulate percentage",
  ORDEN:"Order",
  ACUMULADO:"Accumulate",
  TOTAL:"Total",
  UNITARIO:"Unit",
  NO_HAY_DATOS_REDIRIGIR:"There are no data to show you will be redirected to the previous menu",







  /*
    contrato_detalle.html
    */
    INFORMACION_CONTRATO: "Contract information",
    VIGENCIA: "Validity",
    FORMA_PAGO: "Way to pay",
    SEDE_SOLICITANTE: "Applicant seat",
    NUMERO_CDP: "Number of CDP",
    NUMERO_NECESIDAD: "Need number",
    OBJETO_CDP: "Purpose of the CDP",
    JUSTIFICACION: "Justification",
    DESCRIPCION_FORMA_PAGO: "Description of payment method",
    UNIDAD_EJECUTORA: "Executrix unit",
    MARCO_LEGAL: "Legal framework",
    OBJETO: "Object",
    OBSERVACIONES: "Observations",
    /*
    Contrato_resumen.html
    */
    DOCENTES_CONTRATADOS: "Teachers hired - current period",
    NOMBRE: "Name",
    CEDULA: "Identification card",
    EXPEDICION: "Issued",
    CATEGORIA: "Category",
    DEDICACION: "Dedication",
    HORAS_SEMANALES: "Weekly hours",
    PERIODO_VINCULACION: "Entailment period",
    VALOR_CONTRATO: "Value of contract",
    /*
  Contrato_registro.html
  */
  DATOS_BASICOS: "Basic contract information",
  DISPONIBILIDAD: "Availability",
  JUSTIFICACION_Y_OBSERVACIONES: "Justification and observations",
    /*
    Experiencia_laboral_detalle.html
    */
    EXPERIENCIA_LABORAL_DOCENTE: "Teaching work experience",
    TIPO_ACTIVIDAD: "Type of activity",
    CAMPO_ENSEÑANZA: "Field of instruction",
    INICIO: "Start",
    FINALIZACION: "Ending",
    INSTITUCION: "Institution",
    PAIS: "Country",
    DEPARTAMENTO: "Department",
    MUNICIPIO: "Municipality",
    LOCALIDAD: "Location",
    TIPO_DEDICACION: "Type of dedication",
    /*
    formacion_academica.html
    */
    FORMACION_ACADEMICA: "Academic training",
    NOMBRE_PROYECTO: "Project's name",
    AREA_CONOCIMIENTO: "Area of knowledge",
    TITULO_DOCENTE: "Degree",
    /*
    hojas_vida_seleccion.html
    */
    HOJAS_VIDA: "Resumes",
    HOJAS_VIDA_INSCRITAS: "Resumes inscribed",
    INFORMACION_BASICA_CONTRATO: "Basic contract information",
    TENGA_CUENTA: "Keep in mind",
    PROYECTO_CURRICULAR: "Curricular project",
    NUMERO_SEMANAS: "Number of weeks",
    NUMERO_HORAS_SEMANALES: "Number of hours per week",
    DEDICACION: "Dedication",
    DOCENTE_PLANTA: "Plant teacher",
    DOCENTE_VINCULADOS: "Entailment professors",
    
    /*
    Informacion_personal.html
    */
    INFORMACION_PERSONAL: "Personal information",
    DOCUMENTO: "Document",
    FECHA_EXPEDICION: "Expedition date",
    PRIMER_NOMBRE: "First name",
    SEGUNDO_NOMBRE: "Second name",
    PRIMER_APELLIDO: "Surname",
    SEGUNDO_APELLIDO: "Second surname",
    PAIS_NACIMIENTO: "Country of birth",
    ESTADO_CIVIL: "Civil status",
    /*
    persona_natural_detalle.html
    */    
    INFORMACION_PERSONA_NATURAL: "Information natural person",
    CIUDAD_EXPEDICION: "Expedition city",
    GENERO: "Gender",
    /*
    resolucion_detalle-html
    */
    RESOLUCION: "Resolution",
    FORMATO_RESOLUCION: "Resolution format",
    VER_DOCENTES: "See teachers hired",
    NUMERO_RESOLUCION: "Resolution number",
    FACULTAD: "Faculty",
    NIVEL_ACADEMICO: "Academic level",
    PREAMBULO: "Preamble",
    CONSIDERANDO: "Considering",
    VISTA_RESOLUCION: "Resolution view",
    VISTA_RESOLUCION_ACTUALIZADA: "View of updated resolution",
    RESUELVE: "Resolves",
    ARTICULO: "Article",
    TEXTO: "Text",
    PARAGRAFO: "Paragraph",
    /*
    res_generacion.html
    */
    GENERACION_RESOLUCION: "Generation resolution",
    SELECCIONE: "Select",
    CONSIDERACION: "Consideration",
    RESOLUCIONES: "Resolutions",
    LISTA_RESOLUCIONES: "List of resolutions",
    /*
    trabajos_investigacion.html
    */
    TRABAJOS_INVESTIGACION: "Investigation work",
    NOMBRE_INVESTIGACION: "Name of research",
    AREA_INVESTIGACION: "Area of research",
    TIPO_INVESTIGACION: "Types of research",
    /*
    resolucion_lista.html
    */
    BTN: {
      CREAR_RESOLUCION: "Create new special entailment resolution",
      GENERAR_RESOLUCION: "Generate Resolution",
      REALIZAR_EXPEDICION: "Issue the resolution with the data entered",
      INFORMACION_PERSONA_NATURAL: "Information natural person",
      VINCULAR_DOCENTES_SELECCIONADOS: "Entailment selected teachers to resolution",
      FORMACION_ACADEMICA: "Academic training",
      EXPERIENCIA_LABORAL_DOCENTE: "Teaching work experience",
      TRABAJOS_INVESTIGACION: "Investigation work",
    },    
    /*
    Scrits
    Hoja de vida seleccion.js
    */
    ALERTA: "Alert",
    ACEPTAR: "Accept",
    MENSAJE_ERROR: "Data could not be found for the selected person",
    NUMERO_VINCULACIONES: "Number of entailments made: ",
    VALOR_CONTRATO_FORMATO: "Value of contract: $",
    MONEDA_CORRIENTE: " (Common currency: ",
    SALARIO_NO_CALCULADO1: "The salary of ",
    SALARIO_NO_CALCULADO2: " could not be calculated",
    VALIDAR_CONTRATO: "The assigned values are not valid for the current resolution, please refer to the tab Keep in mind in order to see the rules.",
    DOCUMENTO_ID: "DOCUMENT",
    REGISTRAR_CONTRATOS: "There are teachers with a link to the current resolution, do you want to continue with the entailment?",
    AGREGAR_CONTRATO: "Add new contract",
    CANCELAR: "Cancel",
    CANCELADO: "Cancelled",
    REGISTRO_CANCELADO: "Registration has been canceled",
    PREGUNTA_SEGURO: "Are you sure?",
    CONFIRMAR_DESVINCULACION: "You wish to confirm the teacher's disengagement",
    DEVINCULAR_DOCENTE: "Unveil teacher",
    DESVINCULACION_CANCELADA: "Entailment has been canceled",
    HCH: "Time chair professors: ",
    HCH1: "Between 4 and 8 hours a week.",
    HCP: "Benefits hour chair: ",
    HCP1: "Between 8 and 16 hours a week.",
    MTO: "Occasional half time: ",
    MTO1: "Between 16 and 20 hours a week.",
    TCO: "Casual Full Time: ",
    TCO1: "Between 24 and 40 hours per week.",
    SEMANAS: "Weeks",
    REGLAS: "Rules",
    PROBLEMA: "Problem",
    VER_INFO_PERSONAL_BTN: "See personal information",
    VER_INFO_ACADEMICA: "See Academic Information",
    VER_EXP_LABORAL: "See work experience",
    VER_TRABAJOS_INVESTIGACION: "See the research papers",
    BORRAR_BTN: "Delete",

    UN: "ONE",
    DOS: "TWO",
    TRES: "THREE",
    CUATRO: "FOUR",
    CINCO: "FIVE",
    SEIS: "SIX",
    SIETE: "SEVEN",
    OCHO: "EIGHT",
    NUEVE: "NINE",
    DIEZ: "TEN",
    ONCE: "ELEVEN",
    DOCE: "TWELVE",
    TRECE: "THIRTEEN",
    CATORCE: "FOURTEEN",
    QUINCE: "FIFTEEN",


    DIECISEIS: "SIXTEEN",
    DIECISIETE: "SEVENTEEN",
    DIECIOCHO: "EIGHTEEN",
    DIECINUEVE: "NINETEEN",


    VEINTE: "TWENTY",

    VEINTIUNO: "TWENTY ONE",
    VEINTIDOS: "TWENTY TWO",
    VEINTITRES: "TWENTY THREE",
    VEINTICUATRO: "TWENTY FOUR",
    VEINTICINCO: "TWENTY FIVE",
    VEINTISEIS: "TWENTY SIX",
    VEINTISIETE: "TWENTY SEVEN",
    VEINTIOCHO: "TWENTY EIGHT",
    VEINTINUEVE: "TWENTY NINE",

    TREINTA: "THIRTY ",
    CUARENTA: "FORTY ",
    CINCUENTA: "FIFTY ", 
    SESENTA: "SIXTY ",
    SETENTA: "SEVENTY ",
    OCHENTA: "EGHTY ",
    NOVENTA: "NINETY ",
    CIENTO: "ONE HUNDRED ",
    CIEN: "HUNDRED",
    DOSCIENTOS: "TWO HUNDRED ",
    TRESCIENTOS: "THREE HUNDRED ",
    CUATROCIENTOS: "FOUR HUNDRED ",
    QUINIENTOS: "FIVE HUNDRED ",
    SEISCIENTOS: "SIX HUNDRED ",
    SETECIENTOS: "SEVEN HUNDRED ",
    OCHOCIENTOS: "EIGHT HUNDRED ",
    NOVECIENTOS: "NINE HUNDRED ",

    UN_MIL: "ONE THOUSAND", 
    MIL: "THOUSAND",
    UN_MILLON: "ONE MILLION", 
    MILLONES: " MILLION ",
    PESOS: "PESOS",
    PESO: "PESO",
    CON: "WITH",
    CERO: "ZERO",
    Y: "",
    /*
    resolucion_lista.js
    */
    VISTA_PREVIA_RESOLUCION: "Preview resolution",
    CREAR_RESOLUCION: "Crear nueva resolución de vinculación especial",
    NIVEL: "Level",
    /*
    contrato_registro.js
    */
    NO_CALCULADO_SALARIO: "The salary could not be calculated",
    NUMERO: "Number",
    EXPEDIR: "Issue the resolution?",
    SEGURO_EXPEDIR: "Are you sure you want to issue the resolution?",
    EXPEDICION_NO_REALIZADA: "No issuance of the resolution",
    EXPEDIDA: "The resolution has been successfully issued",
    DATOS_REGISTRADOS: "The data of the connections made have been successfully registered",
    PROBLEMA_EXPEDICION: "A problem has arisen in the issuance of the resolution",
    PROBLEMA_DOCENTE_CONTRATADOS: "A problem has arisen in the registration of the data of contracted teachers",
    NO_DOCENTES: "There are no teachers enrolled within the resolution",

    /*
    resolucion_detalle.js
    */
    ESCRIBA_TEXTO: "Write the text of the article",
    DEBE_INSERTAR: "You must enter text.",
    ALMENOS_UNO: "The resolution must have at least one article",
    ESCRIBA_PARAGRAFO: "Enter the text of the paragraph",
    GUARDADO: "Saved",
    GUARDADO_EXITO: "Changes saved successfully",
    PROBLEMA_ALMACENAMIENTO: "There was a problem storing changes",
    REVISE_DATOS_RESOLUCION: "Review the resolution data",    
    /*
    resolucion_administracion.js
    */
    NO_RESTAURACION_RESOLUCION: "Restore of resolution has not been performed",
    NO_CANCELADA_PAGOS: "The resolution can not be canceled because there are payments associated with the bindings.",
    NO_CANCELACION_RESOLUCION: "No cancellation of the resolution.",
    PREGUNTA_RESTAURAR: "Restore resolution?",
    CANCELAR_RESOLUCION: "Cancel the resolution?",
    OPCIONES: "Options",
    VER_BTN: "See",    
    EDITAR_BTN: "Edit",
    CONFIGURAR_BTN: "Set up",
    EXPEDIR_BTN: "Issue",
    CANCELAR_BTN: "Cancel resolution",
    RESTAURAR_BTN: "Restore resolution",
    /*
    contrato_resumen.html
    */
    DOCENTES_CONTRATADOS_ACTUAL: "TEACHERS CONTRACTED - CURRENT PERIOD",

  
};

angular.module('contractualClienteApp')
  .config(function($translateProvider) {
    $translateProvider
      .translations("es", text_es)
      .translations("en", text_en);
    $translateProvider.preferredLanguage("es");
    $translateProvider.useSanitizeValueStrategy("sanitizeParameters");
});
