"use strict";

/**
 * @ngdoc function
 * @name contractualClienteApp.decorator:TextTranslate
 * @description
 * # TextTranslate
 * Decorator of the contractualClienteApp
 */
var text_es = {
  BTN: {
    VER: "Ver",
    SELECCIONAR: "Seleccionar",
    CANCELAR: "Cancelar",
    CONFIRMAR: "Confirmar",
    AGREGAR: "Agregar",
    REGISTRAR: "Registrar",
    SOLICITAR_RP:"Solicitar RP",
    QUITAR_RUBRO: "Quitar",
    APROBAR: "Aprobar",
    RECHAZAR: "Rechazar",
    SOLICITAR_CDP: "Solicitar CDP",
  },
  TITULO: "GENERATOR-OAS",
  MENSAJE_INICIAL: "Ahora puede comenzar con el desarrollo ...",
  SELECCIONAR: "Seleccionar",
  //solicitud_necesidad
  NECESIDADES: "Necesidades",
  NECESIDAD: "Necesidad",
  SOLICITUD: "Solicitud",
  SOLICITUD_NECESIDAD: "Solicitud de Necesidad",
  DURACION: "Duración",
  UNICO_PAGO: "Único Pago",
  HASTA_AGOTAR_PRESUPUESTO: "Hasta Agotar Presupuesto",
  AÑOS: "Años",
  MESES: "Meses",
  DIAS: "Días",
  RESPONSABLES: "Responsables",
  DEPENDENCIA_SOLICITANTE: "Dependencia Solicitante",
  JEFE_DEPENDENCIA_SOLICITANTE: "Jefe Dependencia Solicitante",
  DEPENDENCIA_DESTINO: "Dependencia Destino",
  JEFE_DEPENDENCIA_DESTINO: "Jefe Dependencia Destino",
  ROL: "Rol",
  ORDENADOR_GASTO: "Ordenador del Gasto",
  GENERAL: "General",
  PLAN_ANUAL_ADQUISICIONES: "Plan Anual de Adquisiones",
  ESTUDIO_MERCADO: "Estudio de Mercado",
  ANALISIS_RIESGOS: "Análisis de Riesgos",
  SUPERVISOR: "Supervisor",
  OBJETO_CONTRACTUAL: "Objeto Contractual",
  OBJETO_CONTRATO: "Objeto de Contrato",
  JUSTIFICACION_CONTRATO: "Justificación de Contrato",
  DOCUMENTOS: "Documentos",
  ENLACE: "Enlace",
  ESPECIFICACIONES: "Especificaciones",
  TIPO_SERVICIO: "Tipo de Servicio",
  PERFIL: "Perfil",
  EL_TIPO_DE: "el Tipo de",
  SNIES_AREA: "Snies Área",
  SNIES_NUCLEO_BASICO: "Snies Núcleo Básico",
  CANTIDAD: "Cantidad",
  ACTIVIDADES_ESPECIFICAS: "Actividades Específicas",
  ELEMENTOS: "Elementos",
  ELEMENTO: "Elemento",
  UNIDAD_MEDIDA: "Unidad de Medida",
  VALOR_UNITARIO: "Valor Unitario",
  IVA: "IVA",
  VALOR_IVA: "Valor IVA",
  VALOR_TOTAL: "Valor Total",
  REQUISITOS_MINIMOS: "Requisitos mínimos",
  FINANCIACION: "Financiación",
  TIPO_RUBRO: "Tipo de Rubro",
  VALOR_SOLICITADO: "Valor Solicitado",
  TOTAL_FINANCIACION: "Total Financiación",
  //lista_documentos_legales
  MARCO_LEGAL: "Marco Legal",
  NOMBRE_DOCUMENTO: "Nombre del Documento",
  VER: "Ver",
  //lista_actividades_economicas
  ACTIVIDADES_ECONOMICAS: "Actividades Económicas",
  //lista_subgrupos_catalogos
  CATALOGO: "Catálogo",
  PRODCUTOS: "Productos",
  //lista_apropiaciones
  APROPIACIONES: "Apropiaciones",
  APROPIACIONES_VIGENCIA: "Apropiaciones de la Vigencia",
  CODIGO_RUBRO: "Código del Rubro",
  DESCRIPCION_RUBRO: "Descripción del Rubro",
  SALDO: "Saldo",
  //fuentes_apropiacion
  FUENTES_FINANCIAMIENTO_APROPIACION: "Fuentes de Financiamiento de la Apropiación",
  //necesidades
  GESTION_NECESIDADES: "Gestión de Necesidades",
  NUMERO_ELABORACION: "No. de Elaboración",
  //visualizar_necesidad
  DE: "de",
  MONTO: "Monto",
  //SOLICITUD RP
  SELECCIONE_UNA_VIGENCIA:"Seleccione una vigencia diferente",
  RESPONSABLE_DOCUMENTO: "Responsable documento",
  RESPONSABLE: "Responsable",
  DATOS_APROPIACIONES: "Datos de las apropiaciones",
  MODALIDAD_SELECCION: "Modalidad de Selección",
  CONTRATO: "Contrato",
  VIGENCIA_CONTRATO: "Vigencia contrato",
  FUENTE:"Fuente de Financiamiento",
  SOLICITUD_PERSONAS:"Contratos para solicitud del registro presupuestal",
  VIGENCIA_ACTUAL:"Vigencia Actual ",
  VIGENCIA_SELECCIONADA:"Vigencia Seleccionada ",
  SELECCION_CDP:"Selección de CDP",
  UNIDAD_EJECUTORA:"Unidad ejecutora",
  ESTADO:"Estado",
  SELECCION_COMPROMISO:"Selección de Compromiso",
  SOLICITUD_RP: "Solicitud Registro Presupuestal",
  DATOS_RP:"Datos del Registro Presupuestal",
  BENEFICIARIO:"Beneficiario",
  NOMBRE_CONTRATISTA: "Nombre",
  DOCUMENTO_CONTRATISTA: "No Documento",
  NOMBRE: "Nombre",
  FUENTE_FINANCIAMIENTO: "Fuente Financiamiento",
  VALOR: "Valor",
  COMPROMISO: "Compromiso",
  NUMERO:"Número",
  VIGENCIA:"Vigencia",
  COMPROMISO_TIPO:"Tipo",
  VALOR_RP:"Valor registro presupuestal",
  SALDO_AP:"Saldo apropiación",
  CDP:"CDP",
  CODIGO: "Código",
  CONSECUTIVO:"Consecutivo",
  OBJETIVO:"Objetivo",
  OBJETO:"Objeto",
  ORDENADOR:"Ordenador",
};

var text_en = {
  TITULO: "GENERATOR-OAS",
  MENSAJE_INICIAL: "Now get to start to develop ...",
  BTN: {
    VER: "See",
    SELECCIONAR: "Choose",
    CANCELAR: "Cancel",
    CONFIRMAR: "Confirm",
    AGREGAR: "Add",
    REGISTRAR: "Register",
    SOLICITAR_RP:"RP request",
    QUITAR_RUBRO: "Delete",
    APROBAR: "Approbe",
    RECHAZAR: "Reject",
    SOLICITAR_CDP: "CDP Request",
  },
  SELECCIONAR: "Select",
  NECESIDADES: "Needs",
  NECESIDAD: "Need",
  SOLICITUD: "Request",
  SOLICITUD_NECESIDAD: "Need Request",
  DURACION: "Duration",
  UNICO_PAGO: "Single Payment",
  HASTA_AGOTAR_PRESUPUESTO: "Until the Budget Had Been Used Up",
  AÑOS: "Years",
  MESES: "Months",
  DIAS: "Days",
  RESPONSABLES: "Responsible",
  DEPENDENCIA_SOLICITANTE: "Requesting Unit",
  JEFE_DEPENDENCIA_SOLICITANTE: "Boss of Requesting Unit",
  DEPENDENCIA_DESTINO: "Destination Unit",
  JEFE_DEPENDENCIA_DESTINO: "Boss of Destination Unit",
  ROL: "Role",
  ORDENADOR_GASTO: "Expenditure Authorizer",
  GENERAL: "General",
  PLAN_ANUAL_ADQUISICIONES: "Annual Procurement Plan",
  ESTUDIO_MERCADO: "Market Survey",
  ANALISIS_RIESGOS: "Risk Analysis",
  SUPERVISOR: "Supervisor",
  OBJETO_CONTRACTUAL: "Contractual Object",
  OBJETO_CONTRATO: "Contract Object",
  JUSTIFICACION_CONTRATO: "Contract Justification",
  DOCUMENTOS: "Documents",
  ENLACE: "Link",
  ESPECIFICACIONES: "Specifications",
  TIPO_SERVICIO: "Type of Service",
  PERFIL: "Profile",
  EL_TIPO_DE: "the Type of",
  SNIES_AREA: "Snies Area",
  SNIES_NUCLEO_BASICO: "Snies Basic Core",
  CANTIDAD: "Quantity",
  ACTIVIDADES_ESPECIFICAS: "Specific Activities",
  ELEMENTOS: "Elements",
  ELEMENTO: "Element",
  UNIDAD_MEDIDA: "Unit of Measurement",
  VALOR_UNITARIO: "Unit Value",
  IVA: "IVA",
  VALOR_IVA: "IVA Value",
  VALOR_TOTAL: "Total Value",
  REQUISITOS_MINIMOS: "Minimum Requirements",
  FINANCIACION: "Financing",
  TIPO_RUBRO: "Type of Line Item",
  VALOR_SOLICITADO: "Requested Value",
  TOTAL_FINANCIACION: "Total Financing",
  //lista_documentos_legales
  MARCO_LEGAL: "Legal Framework",
  NOMBRE_DOCUMENTO: "Document Name",
  VER: "Details",
  //lista_actividades_economicas
  ACTIVIDADES_ECONOMICAS: "Economic Activities",
  //lista_subgrupos_catalogos
  CATALOGO: "Catalogue",
  PRODCUTOS: "Products",
  //lista_apropiaciones
  APROPIACIONES: "Appropiations",
  APROPIACIONES_VIGENCIA: "Validity Appropiations of",
  CODIGO_RUBRO: "Line Item Code",
  DESCRIPCION_RUBRO: "Line Item Description",
  SALDO: "Balance",
  //fuentes_apropiacion
  FUENTES_FINANCIAMIENTO_APROPIACION: "Appropiations Funding Source",
  //necesidades
  GESTION_NECESIDADES: "Managment Needs",
  NUMERO_ELABORACION: "No. of Elaboration",
  //visualizar_necesidad
  DE: "of",
  MONTO: "Amount",
  //SOLICITUD RP
  RESPONSABLE_DOCUMENTO: "Person responsible identification",
  SELECCIONE_UNA_VIGENCIA:"Choose a diferente validity",
  RESPONSABLE: "Person responsible",
  DATOS_APROPIACIONES: "Appropiation data",
  MODALIDAD_SELECCION: "Selection method",
  CONTRATO: "Contract",
  VIGENCIA_CONTRATO: "Contract validity",
  FUENTE:"Source",
  SOLICITUD_PERSONAS:"Contracts for budget registers",
  VIGENCIA_ACTUAL:"Current validity",
  VIGENCIA_SELECCIONADA:"Chosen validity",
  SELECCION_CDP:"CDP choise",
  UNIDAD_EJECUTORA:"Performer unity",
  ESTADO:"State",
  SELECCION_COMPROMISO:"Agreement choose",
  SOLICITUD_RP: "Budget register request",
  DATOS_RP:"Buget register data",
  BENEFICIARIO:"Beneficiary",
  NOMBRE_CONTRATISTA: "Name",
  DOCUMENTO_CONTRATISTA: "Identification",
  NOMBRE: "Name",
  FUENTE_FINANCIAMIENTO: "Funding source",
  VALOR: "Value",
  COMPROMISO: "Agreement",
  NUMERO:"Number",
  VIGENCIA:"Validity",
  COMPROMISO_TIPO:"Tipe",
  VALOR_RP:"Budget register value",
  SALDO_AP:"Appropiation reminder",
  CDP:"CDP",
  CODIGO: "Code",
  CONSECUTIVO:"Consecutive",
  OBJETIVO:"Objective",
  OBJETO:"Object",
  ORDENADOR:"Authorizer",
};

angular.module('contractualClienteApp')
  .config(function($translateProvider) {
    $translateProvider
      .translations("es", text_es)
      .translations("en", text_en);
    $translateProvider.preferredLanguage("es");
    $translateProvider.useSanitizeValueStrategy("sanitizeParameters");
});
